### ISSUE TITLE
[BUG]: Possible memory corruption in docstrings

### ISSUE THREAD

**Issue by matthewdcong** [wjakob/nanobind#392]
### Problem description

It appears that the docstring argument maintains a pointer/reference to the C string that is passed in, which then lends itself to memory corruption when the string goes out of scope after the binding code is executed. This either appears as garbage in the docstring when `pydoc` is executed, e.g. the docstring for `name(...)` as follows

```
    class Animal(builtins.object)
     |  Methods defined here:
     |  
     |  __init__(...)
     |      __init__(self) -> None
     |  
     |  name(...)
     |      name(self) -> str
     |      
     |      ^Pf^]^A
     |  
     |  what(...)
     |      what(self) -> str
```

or `pydoc` fails with a `UnicodeDecodeError`, presumably from decoding a garbage string:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/pydoc.py", line 2751, in <module>
    cli()
  File "/usr/lib/python3.8/pydoc.py", line 2713, in cli
    help.help(arg)
  File "/usr/lib/python3.8/pydoc.py", line 1971, in help
    elif request: doc(request, 'Help on %s:', output=self._output)
  File "/usr/lib/python3.8/pydoc.py", line 1694, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/lib/python3.8/pydoc.py", line 1687, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/usr/lib/python3.8/pydoc.py", line 384, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/usr/lib/python3.8/pydoc.py", line 1183, in docmodule
    contents.append(self.document(value, key, name))
  File "/usr/lib/python3.8/pydoc.py", line 385, in document
    if inspect.isclass(object): return self.docclass(*args)
  File "/usr/lib/python3.8/pydoc.py", line 1352, in docclass
    attrs = spill("Methods %s:\n" % tag, attrs,
  File "/usr/lib/python3.8/pydoc.py", line 1298, in spill
    push(self.document(value,
  File "/usr/lib/python3.8/pydoc.py", line 386, in document
    if inspect.isroutine(object): return self.docroutine(*args)
  File "/usr/lib/python3.8/pydoc.py", line 1429, in docroutine
    doc = getdoc(object) or ''
  File "/usr/lib/python3.8/pydoc.py", line 99, in getdoc
    result = inspect.getdoc(object) or inspect.getcomments(object)
  File "/usr/lib/python3.8/inspect.py", line 613, in getdoc
    doc = object.__doc__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 20: invalid start byte
```

Note that this does not manifest with string literals which have a different lifetime entirely. Is it intended that the docstring argument maintains a pointer/reference to the C string that specifies it? If so, that makes it cumbersome to build docstrings on the fly which is often needed to avoid code duplication when binding instances of a templatized class.

### Reproducible example code

```text
See (latest commit in) https://github.com/matthewdcong/nanobind/tree/bug_repro/docstring_memory_corruption

Build the tests and run `pydoc test_classes_ext` in the tests directory.
```

**Comment by matthewdcong** [comment]
Possible fix in the PR linked above.
